# Generated by Django 5.2 on 2025-05-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждено'), ('canceled', 'Отменено')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='zonebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждено'), ('canceled', 'Отменено')], default='pending', max_length=10),
        ),
    ]
