# Generated by Django 5.2 on 2025-05-16 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_roombooking_status_zonebooking_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZoneBooking',
        ),
    ]
