# Generated by Django 5.2 on 2025-05-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bathorbbqzonebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathorbbqzonebooking',
            name='hours',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
