# Generated by Django 5.2 on 2025-05-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_delete_zonebooking'),
        ('zones', '0002_room_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BathOrBBQZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_type', models.CharField(choices=[('bath', 'Баня'), ('bbq', 'Барбекю')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bathbbq_images/')),
            ],
        ),
        migrations.CreateModel(
            name='EntertainmentZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='entertainment_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
